on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: marketing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Access Amazon Web Services
        uses: shinyinc/action-aws-cli@v1.2
      - name: Connect to Bucket s3
        run: aws s3 sync dist s3://${{ secrets.AWS_BUCKET_S3_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
